/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6p2_emilianoagurcia;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author emili
 */
public class Main extends javax.swing.JFrame {
Random random = new Random();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        //Crear Persona
        CP_Panel_Gerente.setVisible(false);
        CP_Panel_General.setVisible(false);
        //Fin Crear Persona
        
        
        //Crear Objeto
        CO_Panel_Zapato.setVisible(false);
        CO_Panel_Ropa.setVisible(false);
        CO_Panel_Hogar.setVisible(false);
        //Fin Crear Objeto
        
        //Modificar Persona
        CP_Panel_General1.setVisible(false);
        CP_Panel_Gerente1.setVisible(false);
        //Fin Modificar Persona
        
        CP_RBT_SexoM.setSelected(true);
        CP_RBT_EstadoSoltero.setSelected(true);
    }
    ArrayList <Persona> Personas = new ArrayList();
    ArrayList <String> IDs = new ArrayList();
    
    ArrayList <Objeto> Objetos = new ArrayList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CP_Sexo = new javax.swing.ButtonGroup();
        CP_EstadoCivil = new javax.swing.ButtonGroup();
        CO_Talla_Zapato = new javax.swing.ButtonGroup();
        CO_Talla_Ropa = new javax.swing.ButtonGroup();
        BACKGROUND = new javax.swing.JPanel();
        TabbedPane = new javax.swing.JTabbedPane();
        Tab_CP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CP_CB_TipoPersona = new javax.swing.JComboBox<>();
        CP_TF_Nombre = new javax.swing.JTextField();
        CP_SP_Edad = new javax.swing.JSpinner();
        CP_RBT_SexoM = new javax.swing.JRadioButton();
        CP_RBT_SexoF = new javax.swing.JRadioButton();
        CP_RBT_EstadoSoltero = new javax.swing.JRadioButton();
        CP_RBT_EstadoCasado = new javax.swing.JRadioButton();
        CP_SP_Peso = new javax.swing.JSpinner();
        jTextField1 = new javax.swing.JTextField();
        CP_SP_Altura = new javax.swing.JSpinner();
        BT_CP_Agregar = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        CP_Panel_General = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        CP_General_TiempoTrabajando = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CP_General_Ocupacion = new javax.swing.JTextField();
        CP_General_Horario = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        CP_General_Sueldo = new javax.swing.JSpinner();
        jTextField8 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        CP_Panel_Gerente = new javax.swing.JPanel();
        CP_Gerente_Usuario = new javax.swing.JTextField();
        CP_Gerente_Cargo = new javax.swing.JComboBox<>();
        CP_Gerente_Password = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CP_TF_ID = new javax.swing.JTextField();
        Tab_CO = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        CO_BT_Color = new javax.swing.JButton();
        CO_CB_TipoObjeto = new javax.swing.JComboBox<>();
        CO_CB_PersonaIngreso = new javax.swing.JComboBox<>();
        CO_TF_Marca = new javax.swing.JTextField();
        CO_Panel_Zapato = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        CO_Zapato_Talla_L = new javax.swing.JRadioButton();
        CO_Zapato_Talla_XL = new javax.swing.JRadioButton();
        CO_Zapato_Talla_M = new javax.swing.JRadioButton();
        CO_Zapato_Talla_S = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        CO_Zapato_Descripcion = new javax.swing.JTextArea();
        CO_Zapato_Comodidad = new javax.swing.JSpinner();
        CO_Panel_Ropa = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        CO_Ropa_Talla_L = new javax.swing.JRadioButton();
        CO_Ropa_Talla_XL = new javax.swing.JRadioButton();
        CO_Ropa_Talla_M = new javax.swing.JRadioButton();
        CO_Ropa_Talla_S = new javax.swing.JRadioButton();
        CO_Ropa_TipoTela = new javax.swing.JTextField();
        CO_Ropa_Pais = new javax.swing.JTextField();
        CO_Panel_Hogar = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CO_Hogar_Descripcion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        CO_Hogar_Instrucciones = new javax.swing.JTextArea();
        jSpinner1 = new javax.swing.JSpinner();
        jTextField4 = new javax.swing.JTextField();
        ScrollPane_TextArea = new javax.swing.JScrollPane();
        CO_TA_Descripcion = new javax.swing.JTextArea();
        CO_TF_Calidad = new javax.swing.JTextField();
        CO_TF_Size = new javax.swing.JTextField();
        BT_CO_Modificar = new javax.swing.JButton();
        Tab_MP = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        CP_TF_Nombre1 = new javax.swing.JTextField();
        CP_SP_Edad1 = new javax.swing.JSpinner();
        CP_RBT_SexoM1 = new javax.swing.JRadioButton();
        CP_RBT_SexoF1 = new javax.swing.JRadioButton();
        CP_RBT_EstadoSoltero1 = new javax.swing.JRadioButton();
        CP_RBT_EstadoCasado1 = new javax.swing.JRadioButton();
        CP_SP_Peso1 = new javax.swing.JSpinner();
        jTextField9 = new javax.swing.JTextField();
        CP_SP_Altura1 = new javax.swing.JSpinner();
        BT_CP_Agregar1 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        CP_Panel_General1 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        CP_General_TiempoTrabajando1 = new javax.swing.JSpinner();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        CP_General_Ocupacion1 = new javax.swing.JTextField();
        CP_General_Horario1 = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        CP_General_Sueldo1 = new javax.swing.JSpinner();
        jTextField12 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        CP_Panel_Gerente1 = new javax.swing.JPanel();
        CP_Gerente_Usuario1 = new javax.swing.JTextField();
        CP_Gerente_Cargo1 = new javax.swing.JComboBox<>();
        CP_Gerente_Password1 = new javax.swing.JPasswordField();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        CP_TF_ID1 = new javax.swing.JTextField();
        ModificarPersona = new javax.swing.JComboBox<>();
        Tab_MO = new javax.swing.JPanel();
        Tab_JP = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTree_Personas = new javax.swing.JTree();
        Tab_JO = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        JTree_Objetos = new javax.swing.JTree();
        Tab_LP = new javax.swing.JPanel();
        Tab_LO = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 100));

        BACKGROUND.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabbedPane.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TabbedPaneFocusGained(evt);
            }
        });

        Tab_CP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel1.setText("Tipo de Persona");
        Tab_CP.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel2.setText("ID");
        Tab_CP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");
        Tab_CP.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel4.setText("Edad");
        Tab_CP.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel5.setText("Sexo");
        Tab_CP.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel6.setText("Estado Civil");
        Tab_CP.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel7.setText("Altura");
        Tab_CP.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel8.setText("Peso");
        Tab_CP.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, -1, -1));

        CP_CB_TipoPersona.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CP_CB_TipoPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Personal General" }));
        CP_CB_TipoPersona.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CP_CB_TipoPersonaItemStateChanged(evt);
            }
        });
        Tab_CP.add(CP_CB_TipoPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 230, -1));

        CP_TF_Nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tab_CP.add(CP_TF_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 230, -1));

        CP_SP_Edad.setModel(new javax.swing.SpinnerNumberModel(20, 10, 100, 1));
        Tab_CP.add(CP_SP_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        CP_Sexo.add(CP_RBT_SexoM);
        CP_RBT_SexoM.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CP_RBT_SexoM.setText("M");
        Tab_CP.add(CP_RBT_SexoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        CP_Sexo.add(CP_RBT_SexoF);
        CP_RBT_SexoF.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CP_RBT_SexoF.setText("F");
        Tab_CP.add(CP_RBT_SexoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        CP_EstadoCivil.add(CP_RBT_EstadoSoltero);
        CP_RBT_EstadoSoltero.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CP_RBT_EstadoSoltero.setText("Soltero");
        Tab_CP.add(CP_RBT_EstadoSoltero, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

        CP_EstadoCivil.add(CP_RBT_EstadoCasado);
        CP_RBT_EstadoCasado.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CP_RBT_EstadoCasado.setText("Casado");
        Tab_CP.add(CP_RBT_EstadoCasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        CP_SP_Peso.setModel(new javax.swing.SpinnerNumberModel(120.0d, null, null, 0.1d));
        Tab_CP.add(CP_SP_Peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 80, -1));

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("lbs.");
        Tab_CP.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 40, -1));

        CP_SP_Altura.setModel(new javax.swing.SpinnerNumberModel(150.0d, null, null, 0.1d));
        Tab_CP.add(CP_SP_Altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 80, -1));

        BT_CP_Agregar.setText("Agregar Persona");
        BT_CP_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_CP_AgregarMouseClicked(evt);
            }
        });
        Tab_CP.add(BT_CP_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, 220, 60));

        jTextField3.setEditable(false);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setText("cm");
        Tab_CP.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 40, -1));

        CP_Panel_General.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        CP_Panel_General.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel15.setText("Horario");
        CP_Panel_General.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Lps.");
        CP_Panel_General.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 80, -1));

        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel16.setText("Tiempo Trabajando");
        CP_Panel_General.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        CP_General_TiempoTrabajando.setModel(new javax.swing.SpinnerNumberModel());
        CP_Panel_General.add(CP_General_TiempoTrabajando, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 70, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Personas Generales");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CP_Panel_General.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 510, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel14.setText("Ocupación");
        CP_Panel_General.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        CP_General_Ocupacion.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CP_Panel_General.add(CP_General_Ocupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 200, -1));

        CP_General_Horario.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CP_General_Horario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CP_General_HorarioActionPerformed(evt);
            }
        });
        CP_Panel_General.add(CP_General_Horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 200, -1));

        jLabel54.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel54.setText("Sueldo");
        CP_Panel_General.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        CP_General_Sueldo.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.5d));
        CP_Panel_General.add(CP_General_Sueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 70, -1));

        jTextField8.setEditable(false);
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("Semanas");
        CP_Panel_General.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 80, -1));

        Tab_CP.add(CP_Panel_General, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, -1, 260));

        jLabel24.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("CREAR PERSONA");
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tab_CP.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1270, -1));

        CP_Panel_Gerente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));
        CP_Panel_Gerente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CP_Gerente_Usuario.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CP_Panel_Gerente.add(CP_Gerente_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 200, -1));

        CP_Gerente_Cargo.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CP_Gerente_Cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente de Planta", "Gerente de Sucursal" }));
        CP_Panel_Gerente.add(CP_Gerente_Cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 170, -1));

        CP_Gerente_Password.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CP_Panel_Gerente.add(CP_Gerente_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 200, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel13.setText("Cargo");
        CP_Panel_Gerente.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel12.setText("Contraseña");
        CP_Panel_Gerente.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel11.setText("Usuario");
        CP_Panel_Gerente.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Gerente");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CP_Panel_Gerente.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 510, -1));

        Tab_CP.add(CP_Panel_Gerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 510, 240));

        CP_TF_ID.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        Tab_CP.add(CP_TF_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 230, -1));

        TabbedPane.addTab("Crear Persona", Tab_CP);

        Tab_CO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel17.setText("Tipo de Objeto");
        Tab_CO.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel18.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel18.setText("Color");
        Tab_CO.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel19.setText("Descripción");
        Tab_CO.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 80, -1));

        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel20.setText("Marca");
        Tab_CO.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 50, -1));

        jLabel21.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel21.setText("Tamaño");
        Tab_CO.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));

        jLabel22.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel22.setText("Calidad");
        Tab_CO.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, -1, -1));

        jLabel23.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel23.setText("Persona que lo ingresó");
        Tab_CO.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, -1, -1));

        CO_BT_Color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CO_BT_ColorMouseClicked(evt);
            }
        });
        Tab_CO.add(CO_BT_Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, 30));

        CO_CB_TipoObjeto.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CO_CB_TipoObjeto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zapato", "Ropa", "Hogar" }));
        CO_CB_TipoObjeto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CO_CB_TipoObjetoItemStateChanged(evt);
            }
        });
        Tab_CO.add(CO_CB_TipoObjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 110, 20));

        CO_CB_PersonaIngreso.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        Tab_CO.add(CO_CB_PersonaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 310, 20));

        CO_TF_Marca.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        Tab_CO.add(CO_TF_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 310, -1));

        CO_Panel_Zapato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        CO_Panel_Zapato.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("ZAPATO");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CO_Panel_Zapato.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 580, -1));

        jLabel26.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel26.setText("Talla");
        CO_Panel_Zapato.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel27.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel27.setText("Comodidad");
        CO_Panel_Zapato.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel28.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel28.setText("Descripción de la Suela");
        CO_Panel_Zapato.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        CO_Talla_Zapato.add(CO_Zapato_Talla_L);
        CO_Zapato_Talla_L.setText("L");
        CO_Panel_Zapato.add(CO_Zapato_Talla_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        CO_Talla_Zapato.add(CO_Zapato_Talla_XL);
        CO_Zapato_Talla_XL.setText("XL");
        CO_Zapato_Talla_XL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CO_Zapato_Talla_XLActionPerformed(evt);
            }
        });
        CO_Panel_Zapato.add(CO_Zapato_Talla_XL, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 110, -1, -1));

        CO_Talla_Zapato.add(CO_Zapato_Talla_M);
        CO_Zapato_Talla_M.setText("M");
        CO_Panel_Zapato.add(CO_Zapato_Talla_M, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        CO_Talla_Zapato.add(CO_Zapato_Talla_S);
        CO_Zapato_Talla_S.setSelected(true);
        CO_Zapato_Talla_S.setText("S");
        CO_Panel_Zapato.add(CO_Zapato_Talla_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        CO_Zapato_Descripcion.setColumns(20);
        CO_Zapato_Descripcion.setRows(5);
        jScrollPane3.setViewportView(CO_Zapato_Descripcion);

        CO_Panel_Zapato.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        CO_Zapato_Comodidad.setModel(new javax.swing.SpinnerNumberModel(5, 1, 10, 1));
        CO_Panel_Zapato.add(CO_Zapato_Comodidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        Tab_CO.add(CO_Panel_Zapato, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 580, 320));

        CO_Panel_Ropa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 51)));
        CO_Panel_Ropa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("ROPA");
        jLabel29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CO_Panel_Ropa.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 580, -1));

        jLabel30.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel30.setText("País de Elaboración");
        CO_Panel_Ropa.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel31.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel31.setText("Talla");
        CO_Panel_Ropa.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel32.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel32.setText("Tipo de Tela");
        CO_Panel_Ropa.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        CO_Talla_Ropa.add(CO_Ropa_Talla_L);
        CO_Ropa_Talla_L.setText("L");
        CO_Panel_Ropa.add(CO_Ropa_Talla_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        CO_Talla_Ropa.add(CO_Ropa_Talla_XL);
        CO_Ropa_Talla_XL.setText("XL");
        CO_Ropa_Talla_XL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CO_Ropa_Talla_XLActionPerformed(evt);
            }
        });
        CO_Panel_Ropa.add(CO_Ropa_Talla_XL, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        CO_Talla_Ropa.add(CO_Ropa_Talla_M);
        CO_Ropa_Talla_M.setText("M");
        CO_Panel_Ropa.add(CO_Ropa_Talla_M, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        CO_Talla_Ropa.add(CO_Ropa_Talla_S);
        CO_Ropa_Talla_S.setText("S");
        CO_Panel_Ropa.add(CO_Ropa_Talla_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        CO_Ropa_TipoTela.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CO_Panel_Ropa.add(CO_Ropa_TipoTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 160, -1));

        CO_Ropa_Pais.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CO_Panel_Ropa.add(CO_Ropa_Pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        Tab_CO.add(CO_Panel_Ropa, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 580, 320));

        CO_Panel_Hogar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0)));
        CO_Panel_Hogar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("HOGAR");
        jLabel33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CO_Panel_Hogar.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 580, -1));

        jLabel34.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel34.setText("Descripción");
        CO_Panel_Hogar.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel35.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel35.setText("Tiempo de Garantía");
        CO_Panel_Hogar.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel36.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel36.setText("Instrucciones");
        CO_Panel_Hogar.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        CO_Hogar_Descripcion.setColumns(20);
        CO_Hogar_Descripcion.setRows(5);
        jScrollPane1.setViewportView(CO_Hogar_Descripcion);

        CO_Panel_Hogar.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        CO_Hogar_Instrucciones.setColumns(20);
        CO_Hogar_Instrucciones.setRows(5);
        jScrollPane2.setViewportView(CO_Hogar_Instrucciones);

        CO_Panel_Hogar.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(6, 6, null, 6));
        CO_Panel_Hogar.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        jTextField4.setEditable(false);
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField4.setText("cm");
        CO_Panel_Hogar.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 40, -1));

        Tab_CO.add(CO_Panel_Hogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 580, 320));

        CO_TA_Descripcion.setColumns(20);
        CO_TA_Descripcion.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        CO_TA_Descripcion.setRows(5);
        ScrollPane_TextArea.setViewportView(CO_TA_Descripcion);

        Tab_CO.add(ScrollPane_TextArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 310, 130));

        CO_TF_Calidad.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CO_TF_Calidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CO_TF_CalidadActionPerformed(evt);
            }
        });
        Tab_CO.add(CO_TF_Calidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 310, -1));

        CO_TF_Size.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        Tab_CO.add(CO_TF_Size, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 310, -1));

        BT_CO_Modificar.setText("Agregar Objeto");
        BT_CO_Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_CO_ModificarMouseClicked(evt);
            }
        });
        Tab_CO.add(BT_CO_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, 220, 60));

        TabbedPane.addTab("Crear Objeto", Tab_CO);

        Tab_MP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel55.setText("Persona a Modificar");
        Tab_MP.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel56.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel56.setText("ID");
        Tab_MP.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        jLabel57.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel57.setText("Nombre");
        Tab_MP.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jLabel58.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel58.setText("Edad");
        Tab_MP.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        jLabel59.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel59.setText("Sexo");
        Tab_MP.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        jLabel60.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel60.setText("Estado Civil");
        Tab_MP.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        jLabel61.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel61.setText("Altura");
        Tab_MP.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));

        jLabel62.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel62.setText("Peso");
        Tab_MP.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, -1, -1));

        CP_TF_Nombre1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tab_MP.add(CP_TF_Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 230, -1));

        CP_SP_Edad1.setModel(new javax.swing.SpinnerNumberModel(20, 10, 100, 1));
        Tab_MP.add(CP_SP_Edad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        CP_Sexo.add(CP_RBT_SexoM1);
        CP_RBT_SexoM1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CP_RBT_SexoM1.setSelected(true);
        CP_RBT_SexoM1.setText("M");
        Tab_MP.add(CP_RBT_SexoM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        CP_Sexo.add(CP_RBT_SexoF1);
        CP_RBT_SexoF1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CP_RBT_SexoF1.setText("F");
        Tab_MP.add(CP_RBT_SexoF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        CP_EstadoCivil.add(CP_RBT_EstadoSoltero1);
        CP_RBT_EstadoSoltero1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CP_RBT_EstadoSoltero1.setSelected(true);
        CP_RBT_EstadoSoltero1.setText("Soltero");
        Tab_MP.add(CP_RBT_EstadoSoltero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

        CP_EstadoCivil.add(CP_RBT_EstadoCasado1);
        CP_RBT_EstadoCasado1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CP_RBT_EstadoCasado1.setText("Casado");
        Tab_MP.add(CP_RBT_EstadoCasado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        CP_SP_Peso1.setModel(new javax.swing.SpinnerNumberModel(120.0d, null, null, 0.1d));
        Tab_MP.add(CP_SP_Peso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 80, -1));

        jTextField9.setEditable(false);
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField9.setText("lbs.");
        Tab_MP.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 40, -1));

        CP_SP_Altura1.setModel(new javax.swing.SpinnerNumberModel(150.0d, null, null, 0.1d));
        Tab_MP.add(CP_SP_Altura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 80, -1));

        BT_CP_Agregar1.setText("Modificar Persona");
        BT_CP_Agregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_CP_Agregar1MouseClicked(evt);
            }
        });
        Tab_MP.add(BT_CP_Agregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, 220, 60));

        jTextField10.setEditable(false);
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField10.setText("cm");
        Tab_MP.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 40, -1));

        CP_Panel_General1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        CP_Panel_General1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel63.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel63.setText("Horario");
        CP_Panel_General1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jTextField11.setEditable(false);
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("Lps.");
        CP_Panel_General1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 80, -1));

        jLabel64.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel64.setText("Tiempo Trabajando");
        CP_Panel_General1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        CP_General_TiempoTrabajando1.setModel(new javax.swing.SpinnerNumberModel());
        CP_Panel_General1.add(CP_General_TiempoTrabajando1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 70, -1));

        jLabel65.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("Personas Generales");
        jLabel65.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CP_Panel_General1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 510, -1));

        jLabel66.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel66.setText("Ocupación");
        CP_Panel_General1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        CP_General_Ocupacion1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CP_Panel_General1.add(CP_General_Ocupacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 200, -1));

        CP_General_Horario1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CP_General_Horario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CP_General_Horario1ActionPerformed(evt);
            }
        });
        CP_Panel_General1.add(CP_General_Horario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 200, -1));

        jLabel67.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel67.setText("Sueldo");
        CP_Panel_General1.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        CP_General_Sueldo1.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.5d));
        CP_Panel_General1.add(CP_General_Sueldo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 70, -1));

        jTextField12.setEditable(false);
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("Semanas");
        CP_Panel_General1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 80, -1));

        Tab_MP.add(CP_Panel_General1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, -1, 260));

        jLabel68.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("MODIFICAR PERSONA");
        jLabel68.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tab_MP.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1270, -1));

        CP_Panel_Gerente1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));
        CP_Panel_Gerente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CP_Gerente_Usuario1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CP_Panel_Gerente1.add(CP_Gerente_Usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 200, -1));

        CP_Gerente_Cargo1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CP_Gerente_Cargo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente de Planta", "Gerente de Sucursal" }));
        CP_Panel_Gerente1.add(CP_Gerente_Cargo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 170, -1));

        CP_Gerente_Password1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        CP_Panel_Gerente1.add(CP_Gerente_Password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 200, -1));

        jLabel69.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel69.setText("Cargo");
        CP_Panel_Gerente1.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel70.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel70.setText("Contraseña");
        CP_Panel_Gerente1.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel71.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel71.setText("Usuario");
        CP_Panel_Gerente1.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel72.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("Gerente");
        jLabel72.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CP_Panel_Gerente1.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 510, -1));

        Tab_MP.add(CP_Panel_Gerente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 510, 240));

        CP_TF_ID1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        Tab_MP.add(CP_TF_ID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 230, -1));

        ModificarPersona.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ModificarPersonaItemStateChanged(evt);
            }
        });
        Tab_MP.add(ModificarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 220, -1));

        TabbedPane.addTab("Modificar Persona", Tab_MP);

        Tab_MO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TabbedPane.addTab("Modificar Objeto", Tab_MO);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("JTree");
        JTree_Personas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane4.setViewportView(JTree_Personas);

        javax.swing.GroupLayout Tab_JPLayout = new javax.swing.GroupLayout(Tab_JP);
        Tab_JP.setLayout(Tab_JPLayout);
        Tab_JPLayout.setHorizontalGroup(
            Tab_JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_JPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1258, Short.MAX_VALUE)
                .addContainerGap())
        );
        Tab_JPLayout.setVerticalGroup(
            Tab_JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_JPLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Jerarquía Personas", Tab_JP);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("JTree");
        JTree_Objetos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane5.setViewportView(JTree_Objetos);

        javax.swing.GroupLayout Tab_JOLayout = new javax.swing.GroupLayout(Tab_JO);
        Tab_JO.setLayout(Tab_JOLayout);
        Tab_JOLayout.setHorizontalGroup(
            Tab_JOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_JOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1258, Short.MAX_VALUE)
                .addContainerGap())
        );
        Tab_JOLayout.setVerticalGroup(
            Tab_JOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_JOLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Jerarquía Objetos", Tab_JO);

        javax.swing.GroupLayout Tab_LPLayout = new javax.swing.GroupLayout(Tab_LP);
        Tab_LP.setLayout(Tab_LPLayout);
        Tab_LPLayout.setHorizontalGroup(
            Tab_LPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );
        Tab_LPLayout.setVerticalGroup(
            Tab_LPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );

        TabbedPane.addTab("Lista Personas", Tab_LP);

        javax.swing.GroupLayout Tab_LOLayout = new javax.swing.GroupLayout(Tab_LO);
        Tab_LO.setLayout(Tab_LOLayout);
        Tab_LOLayout.setHorizontalGroup(
            Tab_LOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );
        Tab_LOLayout.setVerticalGroup(
            Tab_LOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );

        TabbedPane.addTab("Lista Objetos", Tab_LO);

        BACKGROUND.add(TabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BACKGROUND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BACKGROUND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CO_Zapato_Talla_XLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CO_Zapato_Talla_XLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CO_Zapato_Talla_XLActionPerformed

    private void CO_Ropa_Talla_XLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CO_Ropa_Talla_XLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CO_Ropa_Talla_XLActionPerformed

    private void CP_General_HorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CP_General_HorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CP_General_HorarioActionPerformed

    private void CO_TF_CalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CO_TF_CalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CO_TF_CalidadActionPerformed

    private void CP_CB_TipoPersonaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CP_CB_TipoPersonaItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == 1){
            if(CP_CB_TipoPersona.getSelectedItem().equals("Gerente")){
                CP_Panel_Gerente.setVisible(true);
                CP_Panel_General.setVisible(false);
            }else if(CP_CB_TipoPersona.getSelectedItem().equals("Personal General")){
                CP_Panel_Gerente.setVisible(false);
                CP_Panel_General.setVisible(true);
            }
        }
    }//GEN-LAST:event_CP_CB_TipoPersonaItemStateChanged

    private void BT_CP_AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_CP_AgregarMouseClicked
        // TODO add your handling code here:
        
        String EstadoCivil;
        char Sexo;
        DefaultComboBoxModel mCO_CB_PersonaIngreso = (DefaultComboBoxModel) CO_CB_PersonaIngreso.getModel();
        DefaultComboBoxModel mModificarPersona = (DefaultComboBoxModel) ModificarPersona.getModel();
        
        if(CP_RBT_EstadoSoltero.isSelected()){
            EstadoCivil = "Soltero";
        }else{
            EstadoCivil = "Casado";
        }
        
        if(CP_RBT_SexoM.isSelected()){
            Sexo = 'M';
        }else{
            Sexo = 'F';
        }

        if (IDs.contains(CP_TF_ID.getText())) {
            JOptionPane.showMessageDialog(this, "El ID ya ha sido ingresado, intente denuevo");
        } else {
            try {
                if (CP_CB_TipoPersona.getSelectedItem().toString().equals("Gerente")) {
                    if(CP_TF_ID.getText().isEmpty() || CP_TF_Nombre.getText().isEmpty()
                     ||CP_Gerente_Usuario.getText().isEmpty() || CP_Gerente_Password.getText().isEmpty()){
                        JOptionPane.showMessageDialog(this, "Llene todos los Campos");
                    }else{
                        Gerente newGerente = 
                                new Gerente(
                                        CP_Gerente_Usuario.getText(),
                                        CP_Gerente_Password.getText(),
                                        CP_Gerente_Cargo.getSelectedItem().toString(),
                                        CP_TF_ID.getText(),
                                        CP_TF_Nombre.getText(),
                                        (Integer) CP_SP_Edad.getValue(),
                                        Sexo,
                                        EstadoCivil,
                                        (Double) CP_SP_Altura.getValue(),
                                        (Double) CP_SP_Peso.getValue()
                                );
                        Personas.add(newGerente);    
                        mCO_CB_PersonaIngreso.addElement(newGerente);
                        mModificarPersona.addElement(newGerente);
                        
                        //Arbol
                        DefaultTreeModel ModeloArbol = (DefaultTreeModel) JTree_Personas.getModel();
                        DefaultMutableTreeNode Raiz = (DefaultMutableTreeNode) ModeloArbol.getRoot();
                        
                        DefaultMutableTreeNode Nodo_Persona = new DefaultMutableTreeNode(
                                new Persona(
                                        CP_TF_ID.getText(),
                                        CP_TF_Nombre.getText(),
                                        (Integer) CP_SP_Edad.getValue(),
                                        Sexo,
                                        EstadoCivil,
                                        (Double) CP_SP_Altura.getValue(),
                                        (Double) CP_SP_Peso.getValue()
                                )
                        );
                        
                        DefaultMutableTreeNode Nodo_Gerentes = new DefaultMutableTreeNode();
                        
                        DefaultMutableTreeNode Nodo_Gerente_Planta = new DefaultMutableTreeNode(); 
                        DefaultMutableTreeNode Nodo_Gerente_Sucursal = new DefaultMutableTreeNode(); 
                         
                        Raiz.add(Nodo_Persona);
                        
                        ModeloArbol.reload();
                        
                        //Fin Arbol
                        
                        CP_CB_TipoPersona.setSelectedIndex(0);
                        CP_TF_ID.setText("");
                        CP_TF_Nombre.setText("");
                        CP_SP_Edad.setValue(20);
                        CP_RBT_SexoM.setSelected(true);
                        CP_RBT_EstadoSoltero.setSelected(true);
                        CP_SP_Altura.setValue(150);
                        CP_SP_Peso.setValue(120);
                        
                        CP_Gerente_Usuario.setText("");
                        CP_Gerente_Password.setText("");
                        CP_Gerente_Cargo.setSelectedIndex(0);
                        
                        CP_Panel_General.setVisible(false);
                        CP_Panel_Gerente.setVisible(false);
                    }
                    
                } else if (CP_CB_TipoPersona.getSelectedItem().toString().equals("Personal General")) {
                    if(CP_TF_ID.getText().isEmpty() || CP_TF_Nombre.getText().isEmpty()
                    || CP_General_Ocupacion.getText().isEmpty() || CP_General_Horario.getText().isEmpty()){
                        JOptionPane.showMessageDialog(this, "Llene todos los Campos");
                    }else{
                        General newGeneral =
                                new General(
                                        CP_General_Ocupacion.getText(),
                                        CP_General_Horario.getText(),
                                        (Integer) CP_General_TiempoTrabajando.getValue(),
                                        (Double) CP_General_Sueldo.getValue(),
                                        CP_TF_ID.getText(),
                                        CP_TF_Nombre.getText(),
                                        (Integer) CP_SP_Edad.getValue(),
                                        Sexo,
                                        EstadoCivil,
                                        (Double) CP_SP_Altura.getValue(),
                                        (Double) CP_SP_Peso.getValue()
                                );
                        Personas.add(newGeneral);
                        mCO_CB_PersonaIngreso.addElement(newGeneral);
                        mModificarPersona.addElement(newGeneral);
                        
                        CP_CB_TipoPersona.setSelectedIndex(0);
                        CP_TF_ID.setText("");
                        CP_TF_Nombre.setText("");
                        CP_SP_Edad.setValue(20);
                        CP_RBT_SexoM.setSelected(true);
                        CP_RBT_EstadoSoltero.setSelected(true);
                        CP_SP_Altura.setValue(150);
                        CP_SP_Peso.setValue(120);
                        
                        CP_General_Ocupacion.setText("");
                        CP_General_Horario.setText("");
                        CP_General_TiempoTrabajando.setValue(0);
                        CP_General_Sueldo.setValue(0);
                        
                        CP_Panel_General.setVisible(false);
                        CP_Panel_Gerente.setVisible(false);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Elija un tipo de Persona");
                }
                
                
                
                //Panel Personal General
                
                //Fin Panel Personal General
                
                //Panel Gerente
                
                //Fin Panel Gerente
                
                IDs.add(CP_TF_ID.getText());
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error, no se pudo agregar la persona");
            }
        }
    }//GEN-LAST:event_BT_CP_AgregarMouseClicked

    private void CO_CB_TipoObjetoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CO_CB_TipoObjetoItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == 1){
            if(CO_CB_TipoObjeto.getSelectedItem().toString().equals("Zapato")){
                CO_Panel_Zapato.setVisible(true);
                CO_Panel_Hogar.setVisible(false);
                CO_Panel_Ropa.setVisible(false);
            }else if(CO_CB_TipoObjeto.getSelectedItem().toString().equals("Ropa")){
                CO_Panel_Zapato.setVisible(false);
                CO_Panel_Hogar.setVisible(false);
                CO_Panel_Ropa.setVisible(true);
                
            }else if(CO_CB_TipoObjeto.getSelectedItem().toString().equals("Hogar")){
                CO_Panel_Zapato.setVisible(false);
                CO_Panel_Hogar.setVisible(true);
                CO_Panel_Ropa.setVisible(false);
                
            }else{
                JOptionPane.showMessageDialog(this, "Elija un tipo de Objeto");
            }
        }
    }//GEN-LAST:event_CO_CB_TipoObjetoItemStateChanged

    private void BT_CO_ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_CO_ModificarMouseClicked
        // TODO add your handling code here:
        
        String Talla;
        DefaultComboBoxModel mCO_CB_PersonaIngreso = (DefaultComboBoxModel) CO_CB_PersonaIngreso.getModel();
        
        if(CO_CB_TipoObjeto.getSelectedItem().equals("Zapato")){
            if(CO_TA_Descripcion.getText().isEmpty() || CO_TF_Marca.getText().isEmpty() || CO_TF_Size.getText().isEmpty() || CO_TF_Calidad.getText().isEmpty()
            || CO_Zapato_Descripcion.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Llene todos los Campos");
            }else{
                
                if(CO_Zapato_Talla_S.isSelected()){
                    Talla = "S";
                }else if(CO_Zapato_Talla_M.isSelected()){
                    Talla = "M";
                }else if(CO_Zapato_Talla_L.isSelected()){
                    Talla = "L";
                }else{
                    Talla = "XL";
                }
                
                
                Zapato newZapato = new Zapato(
                        Talla,
                        CO_Zapato_Descripcion.getText(),
                        (Integer) CO_Zapato_Comodidad.getValue(),
                        (Persona) mCO_CB_PersonaIngreso.getSelectedItem(),
                        CO_BT_Color.getBackground(),
                        CO_TA_Descripcion.getText(),
                        CO_TF_Marca.getText(),
                        CO_TF_Size.getText(),
                        CO_TF_Calidad.getText()
                );
                Objetos.add(newZapato);
                CO_Zapato_Descripcion.setText("");
                CO_Zapato_Comodidad.setValue(5);
                CO_TA_Descripcion.setText("");
                CO_TF_Marca.setText("");
                CO_TF_Size.setText("");
                CO_TF_Calidad.setText("");
                
            }
        }else if(CO_CB_TipoObjeto.getSelectedItem().equals("Ropa")){
            if(CO_TA_Descripcion.getText().isEmpty() || CO_TF_Marca.getText().isEmpty() || CO_TF_Size.getText().isEmpty() || CO_TF_Calidad.getText().isEmpty()
            || CO_Ropa_TipoTela.getText().isEmpty() || CO_Ropa_Pais.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Llene todos los Campos");
            }else{
                if(CO_Ropa_Talla_S.isSelected()){
                    Talla = "S";
                }else if(CO_Ropa_Talla_M.isSelected()){
                    Talla = "M";
                }else if(CO_Ropa_Talla_L.isSelected()){
                    Talla = "L";
                }else{
                    Talla = "XL";
                }
                
                Ropa newRopa = new Ropa(
                        Talla,
                        CO_Ropa_TipoTela.getText(),
                        CO_Ropa_Pais.getText(),
                        (Persona) mCO_CB_PersonaIngreso.getSelectedItem(),
                        CO_BT_Color.getBackground(),
                        CO_TA_Descripcion.getText(),
                        CO_TF_Marca.getText(),
                        CO_TF_Size.getText(),
                        CO_TF_Calidad.getText()
                );
                Objetos.add(newRopa);
                
                CO_Ropa_TipoTela.setText("");
                CO_Ropa_Pais.setText("");
                CO_TA_Descripcion.setText("");
                CO_TF_Marca.setText("");
                CO_TF_Size.setText("");
                CO_TF_Calidad.setText("");
            }
        }else if(CO_CB_TipoObjeto.getSelectedItem().equals("Hogar")){
            if(CO_TA_Descripcion.getText().isEmpty() || CO_TF_Marca.getText().isEmpty() || CO_TF_Size.getText().isEmpty() || CO_TF_Calidad.getText().isEmpty()
            || CO_Hogar_Descripcion.getText().isEmpty() || CO_Hogar_Instrucciones.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Llene todos los Campos");
            }else{
                Hogar newHogar = new Hogar(
                        CO_Hogar_Descripcion.getText(),
                        CO_Hogar_Instrucciones.getText(),
                        (Integer) jSpinner1.getValue(),
                        (Persona) mCO_CB_PersonaIngreso.getSelectedItem(),
                        CO_BT_Color.getBackground(),
                        CO_TA_Descripcion.getText(),
                        CO_TF_Marca.getText(),
                        CO_TF_Size.getText(),
                        CO_TF_Calidad.getText()
                );
                Objetos.add(newHogar);
                
                CO_Hogar_Descripcion.setText("");
                CO_Hogar_Instrucciones.setText("");
                jSpinner1.setValue(6);
                CO_TA_Descripcion.setText("");
                CO_TF_Marca.setText("");
                CO_TF_Size.setText("");
                CO_TF_Calidad.setText("");
            }
        }
    }//GEN-LAST:event_BT_CO_ModificarMouseClicked

    private void CO_BT_ColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CO_BT_ColorMouseClicked
        // TODO add your handling code here:
        CO_BT_Color.setBackground(JColorChooser.showDialog(this, "Elegir Color", Color.yellow));
    }//GEN-LAST:event_CO_BT_ColorMouseClicked

    private void BT_CP_Agregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_CP_Agregar1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BT_CP_Agregar1MouseClicked

    private void CP_General_Horario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CP_General_Horario1ActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel mModificarPersona = (DefaultComboBoxModel) ModificarPersona.getModel();
        int index;
        
        if(mModificarPersona.getSelectedItem() instanceof Gerente){
            index = Personas.indexOf( (Gerente) ModificarPersona.getSelectedItem());
            
        }else{
            index = Personas.indexOf( (General) ModificarPersona.getSelectedItem());
            
        }
    }//GEN-LAST:event_CP_General_Horario1ActionPerformed

    private void ModificarPersonaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ModificarPersonaItemStateChanged
        // TODO add your handling code here:
        DefaultComboBoxModel mModificarPersona = (DefaultComboBoxModel) ModificarPersona.getModel();
        
        if(evt.getStateChange() == 1){
            int index;
            
            if(mModificarPersona.getSelectedItem() instanceof Gerente){
                index = Personas.indexOf( (Gerente) ModificarPersona.getSelectedItem());
                CP_Panel_General1.setVisible(false);
                CP_Panel_Gerente1.setVisible(true);
                
                CP_TF_ID1.setText((String) Personas.get(index).getID());
                CP_TF_Nombre1.setText((String) Personas.get(index).getNombre());
                CP_SP_Edad1.setValue(Personas.get(index).getEdad());
                CP_SP_Altura1.setValue(Personas.get(index).getAltura());
                CP_SP_Peso1.setValue(Personas.get(index).getPeso());
                if(Personas.get(index).getSexo() == 'M'){
                    CP_RBT_SexoM1.setSelected(true);
                }else{
                    CP_RBT_SexoF1.setSelected(true);
                }
                
                if(Personas.get(index).getEstadoCivil().equals("Soltero")){
                    CP_RBT_EstadoSoltero1.setSelected(true);
                }else{
                    CP_RBT_EstadoCasado1.setSelected(true);
                }
            }else{
                index = Personas.indexOf( (General) ModificarPersona.getSelectedItem());
                CP_Panel_General1.setVisible(true);
                CP_Panel_Gerente1.setVisible(false);
                
                CP_TF_ID1.setText((String) Personas.get(index).getID());
                CP_TF_Nombre1.setText((String) Personas.get(index).getNombre());
                CP_SP_Edad1.setValue(Personas.get(index).getEdad());
                CP_SP_Altura1.setValue(Personas.get(index).getAltura());
                CP_SP_Peso1.setValue(Personas.get(index).getPeso());
                if(Personas.get(index).getSexo() == 'M'){
                    CP_RBT_SexoM1.setSelected(true);
                }else{
                    CP_RBT_SexoF1.setSelected(true);
                }
                
                if(Personas.get(index).getEstadoCivil().equals("Soltero")){
                    CP_RBT_EstadoSoltero1.setSelected(true);
                }else{
                    CP_RBT_EstadoCasado1.setSelected(true);
                }
            }
        }
    }//GEN-LAST:event_ModificarPersonaItemStateChanged

    private void TabbedPaneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TabbedPaneFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TabbedPaneFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BACKGROUND;
    private javax.swing.JButton BT_CO_Modificar;
    private javax.swing.JButton BT_CP_Agregar;
    private javax.swing.JButton BT_CP_Agregar1;
    private javax.swing.JButton CO_BT_Color;
    private javax.swing.JComboBox<String> CO_CB_PersonaIngreso;
    private javax.swing.JComboBox<String> CO_CB_TipoObjeto;
    private javax.swing.JTextArea CO_Hogar_Descripcion;
    private javax.swing.JTextArea CO_Hogar_Instrucciones;
    private javax.swing.JPanel CO_Panel_Hogar;
    private javax.swing.JPanel CO_Panel_Ropa;
    private javax.swing.JPanel CO_Panel_Zapato;
    private javax.swing.JTextField CO_Ropa_Pais;
    private javax.swing.JRadioButton CO_Ropa_Talla_L;
    private javax.swing.JRadioButton CO_Ropa_Talla_M;
    private javax.swing.JRadioButton CO_Ropa_Talla_S;
    private javax.swing.JRadioButton CO_Ropa_Talla_XL;
    private javax.swing.JTextField CO_Ropa_TipoTela;
    private javax.swing.JTextArea CO_TA_Descripcion;
    private javax.swing.JTextField CO_TF_Calidad;
    private javax.swing.JTextField CO_TF_Marca;
    private javax.swing.JTextField CO_TF_Size;
    private javax.swing.ButtonGroup CO_Talla_Ropa;
    private javax.swing.ButtonGroup CO_Talla_Zapato;
    private javax.swing.JSpinner CO_Zapato_Comodidad;
    private javax.swing.JTextArea CO_Zapato_Descripcion;
    private javax.swing.JRadioButton CO_Zapato_Talla_L;
    private javax.swing.JRadioButton CO_Zapato_Talla_M;
    private javax.swing.JRadioButton CO_Zapato_Talla_S;
    private javax.swing.JRadioButton CO_Zapato_Talla_XL;
    private javax.swing.JComboBox<String> CP_CB_TipoPersona;
    private javax.swing.ButtonGroup CP_EstadoCivil;
    private javax.swing.JTextField CP_General_Horario;
    private javax.swing.JTextField CP_General_Horario1;
    private javax.swing.JTextField CP_General_Ocupacion;
    private javax.swing.JTextField CP_General_Ocupacion1;
    private javax.swing.JSpinner CP_General_Sueldo;
    private javax.swing.JSpinner CP_General_Sueldo1;
    private javax.swing.JSpinner CP_General_TiempoTrabajando;
    private javax.swing.JSpinner CP_General_TiempoTrabajando1;
    private javax.swing.JComboBox<String> CP_Gerente_Cargo;
    private javax.swing.JComboBox<String> CP_Gerente_Cargo1;
    private javax.swing.JPasswordField CP_Gerente_Password;
    private javax.swing.JPasswordField CP_Gerente_Password1;
    private javax.swing.JTextField CP_Gerente_Usuario;
    private javax.swing.JTextField CP_Gerente_Usuario1;
    private javax.swing.JPanel CP_Panel_General;
    private javax.swing.JPanel CP_Panel_General1;
    private javax.swing.JPanel CP_Panel_Gerente;
    private javax.swing.JPanel CP_Panel_Gerente1;
    private javax.swing.JRadioButton CP_RBT_EstadoCasado;
    private javax.swing.JRadioButton CP_RBT_EstadoCasado1;
    private javax.swing.JRadioButton CP_RBT_EstadoSoltero;
    private javax.swing.JRadioButton CP_RBT_EstadoSoltero1;
    private javax.swing.JRadioButton CP_RBT_SexoF;
    private javax.swing.JRadioButton CP_RBT_SexoF1;
    private javax.swing.JRadioButton CP_RBT_SexoM;
    private javax.swing.JRadioButton CP_RBT_SexoM1;
    private javax.swing.JSpinner CP_SP_Altura;
    private javax.swing.JSpinner CP_SP_Altura1;
    private javax.swing.JSpinner CP_SP_Edad;
    private javax.swing.JSpinner CP_SP_Edad1;
    private javax.swing.JSpinner CP_SP_Peso;
    private javax.swing.JSpinner CP_SP_Peso1;
    private javax.swing.ButtonGroup CP_Sexo;
    private javax.swing.JTextField CP_TF_ID;
    private javax.swing.JTextField CP_TF_ID1;
    private javax.swing.JTextField CP_TF_Nombre;
    private javax.swing.JTextField CP_TF_Nombre1;
    private javax.swing.JTree JTree_Objetos;
    private javax.swing.JTree JTree_Personas;
    private javax.swing.JComboBox<String> ModificarPersona;
    private javax.swing.JScrollPane ScrollPane_TextArea;
    private javax.swing.JPanel Tab_CO;
    private javax.swing.JPanel Tab_CP;
    private javax.swing.JPanel Tab_JO;
    private javax.swing.JPanel Tab_JP;
    private javax.swing.JPanel Tab_LO;
    private javax.swing.JPanel Tab_LP;
    private javax.swing.JPanel Tab_MO;
    private javax.swing.JPanel Tab_MP;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
